# Generated by Django 2.0.2 on 2018-02-28 03:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0002_auto_20180224_0348'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='lines',
            field=models.PositiveIntegerField(default=0, help_text='额度'),
        ),
        migrations.AlterField(
            model_name='cashout',
            name='amount',
            field=models.DecimalField(decimal_places=2, help_text='金额', max_digits=11),
        ),
        migrations.AlterField(
            model_name='cashout',
            name='fee',
            field=models.DecimalField(decimal_places=2, help_text='手续费', max_digits=9),
        ),
        migrations.AlterField(
            model_name='cashout',
            name='pos_rate',
            field=models.FloatField(default=0.6, help_text='刷卡费率', verbose_name='rate'),
        ),
        migrations.AlterField(
            model_name='cashout',
            name='swipe_day',
            field=models.DateField(default=datetime.date.today, help_text='刷卡日'),
        ),
    ]
