# Generated by Django 2.0.2 on 2018-03-13 02:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0003_auto_20180228_1145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='creditcard',
            name='tail_no',
            field=models.CharField(max_length=10),
        ),
    ]
