# Generated by Django 2.0.2 on 2018-06-14 13:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0004_auto_20180313_1052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Loans',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ct', models.DateTimeField(auto_now_add=True)),
                ('ut', models.DateTimeField(auto_now=True)),
                ('bank', models.CharField(max_length=100)),
                ('loan_day', models.DateField(default=datetime.date.today, help_text='借款日')),
                ('amount', models.DecimalField(decimal_places=2, help_text='金额', max_digits=11)),
                ('loan_type', models.CharField(choices=[('EPI', '等额本息'), ('EP', '等额本金')], default='EPI', max_length=5)),
                ('due_day', models.DateField(help_text='到期日')),
                ('apr', models.FloatField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
