# Generated by Django 2.0.2 on 2018-06-15 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0005_loans'),
    ]

    operations = [
        migrations.AddField(
            model_name='loans',
            name='debit_day',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
    ]
