# Generated by Django 2.0.2 on 2018-07-09 08:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0006_loans_debit_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='Installment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ct', models.DateTimeField(auto_now_add=True)),
                ('ut', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=2, help_text='金额', max_digits=11)),
                ('stage_count', models.PositiveSmallIntegerField(help_text='分期期数')),
                ('charge_rate', models.FloatField(blank=True, default=0.35, null=True)),
                ('lend_rate', models.FloatField(blank=True, null=True)),
                ('first_repay_day', models.DateField(help_text='第一次还款日')),
                ('balance', models.DecimalField(decimal_places=2, help_text='余额', max_digits=11)),
                ('cashOut', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cc.CashOut')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Staging',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ct', models.DateTimeField(auto_now_add=True)),
                ('ut', models.DateTimeField(auto_now=True)),
                ('no', models.PositiveSmallIntegerField(help_text='第几期')),
                ('pay_amount', models.DecimalField(decimal_places=2, help_text='金额', max_digits=11)),
                ('pay_day', models.DateField(help_text='还款日')),
                ('isRepaid', models.BooleanField(default=False)),
                ('installment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cc.Installment')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='loans',
            name='isRepaid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='installment',
            name='loan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cc.Loans'),
        ),
    ]
