# Generated by Django 2.0.2 on 2018-07-11 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cc', '0007_auto_20180709_1615'),
    ]

    operations = [
        migrations.AddField(
            model_name='staging',
            name='principal',
            field=models.DecimalField(decimal_places=2, default=0, help_text='本金', max_digits=11),
            preserve_default=False,
        ),
    ]
