# Generated by Django 2.0.2 on 2019-04-29 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quant', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailystats',
            name='median_close',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=6),
        ),
    ]
